[package]
name = "ernisto/profilestore"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"

[dependencies]
ProfileService = "surnautica/profileservice@1.0.0"
Promise = "lukadev-0/typed-promise@4.0.2"